---
- hosts: all
  become: true
  tasks:
    - name: Update repository index
      apt:
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install apache2 package
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install php support for apache
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
