---
- hosts: all
  become: true
  tasks:
    - name: Install updates
      apt:
        upgrade: full
        update_cache: true
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
    - name: Install cowsay
      apt:
        name:
          - cowsay
        state: latest
      when: ansible_distribution == "Ubuntu"
