---
- name: Update and autoremove system
  hosts: all
  become: true
  tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - update

    - name: Upgrade system
      apt:
        upgrade: full
      tags:
        - upgrade

    - name: Check reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      tags:
        - check_reboot

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists
      tags:
        - reboot

    - name: Removing unnecessary dependencies
      apt:
        autoremove: true
      tags:
        - autoremove
